### ISSUE TITLE
[Feature Request] EKS Access not supported with TEAM for AWS IAM Identity Center

### ISSUE THREAD

**Issue by amanone** [aws-samples/iam-identity-center-team#113]
Hello :wave:

We've been evaluating the AWS TEAMs ([Temporary Elevated Access Management](https://github.com/aws-samples/iam-identity-center-team)) for integration into our AWS IAM Identity Center environment. However, it seems impossible to use it for EKS access, as every time when Temporary Elevated Access is granted there is a AWS role with unique ID created in the target AWS account. It's not possible to use any kind of regex for AWS role trust relationship or inside EKS aws-auth ConfigMap.

Is there a workaround to predict the AWS role with the unique ID or another way to configure the temporary access for EKS?

Thanks!

**Comment by tawoyinfa** [comment]
Hi @amanone. The AWS role is created by AWS IAM Identity Center in the account once TEAM is used to approve and grant the access. TEAM doesnt have any control on  the ID of the AWS role created in the account by IAM Identity Center.

**Comment by trickyearlobe** [comment]
I also have this issue

There was a PR to address this which never managed to get merged.
It worked by allowing wildcards in the role name.

https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/416

**Comment by logandavies181** [comment]
The code is still there's it's just behind a feature flag and AWS said they wouldn't enable it. When I raised it initially it had full wildcard support (actually [arnLike](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_ARN)) but I was asked to scale it back to just SSO roles.

According to [this comment](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_ARN) they're cooking something up, so maybe @jku8 can ensure that it has interop with this feature.

Or use some of the code that would have solved this two years ago ¯\\\_(ツ)_/¯

**Comment by trickyearlobe** [comment]
Thanks @logandavies181 I was seriously considering using your original wildcard PR but I found a simple workaround for this specific issue, so I can afford to wait till AWS decide what they are going to do to make all the parts fit together.

The fix is basically to create an empty dummy "SSO" group which never gets any users assigned and use that to attach the permission set(s) to the target account(s).

One that's done, there is a permanent IAM role which can be used in the AWS-AUTH config map. When users elevate their permissions, they get the same IAM role, and it's perfectly repeatable.
