### ISSUE TITLE
Permissions Disruption in Team When Google SSO Authorization Expires

### ISSUE THREAD

**Issue by vo-va** [aws-samples/iam-identity-center-team#143]
I suspect that when the Google Single Sign-On (SSO) authorization expires, all requested permissions in Teams that were obtained using the expired token become dysfunctional. This leads to a disruption in the expected functionality of the application.

If this is impossible to fix maybe then may I suggest that if the expiration of the Google SSO (other SSO) authorization is imminent, Teams should proactively force a reauthorization to avoid disruption in service and maintain a seamless user experience.

**Comment by mattcenis** [comment]
Can you please update us on this issue?  We really need alignment of expirations and using refresh tokens.

**Comment by jeffsec-aws** [comment]
Can you elaborate on how you have integrated Google IdP here please:
- From a TEAM portal standpoint
- From an IdC portal Standpoint

Can you elaborate on `all requested permissions in Teams that were obtained using the expired token become dysfunctional` can you:
- Describe the behavior? What works? What fails? What would be the expected behavior?
- Add log of the issue? Error messages?

Thanks

**Comment by mattcenis** [comment]
We use Control tower and in our Control tower AWS Account in IAM Identity Center we have configured an Identity source for “external Identity provider” .   This points to our Google IdP.

We use this for both logging into aws console directly using permission sets provided in IAM Identity Center as well as through TEAM requests.

Currently we have a maximum session duration of 8 hours for the connector between aws and google idp.   Then the employee would need to re-authenticate to AWS using google IdP.  However  if a TEAMs request is requested and approved near the end of that 8 hour session, and the google session expires, it seems like this limits the length of the TEAMs request.

I’ll get back with you with a better description of the problem.

-matt


From: Jeff Lombardo ***@***.***>
Date: Thursday, February 22, 2024 at 12:46 PM
To: aws-samples/iam-identity-center-team ***@***.***>
Cc: Matt Cenis ***@***.***>, Comment ***@***.***>
Subject: Re: [aws-samples/iam-identity-center-team] Permissions Disruption in Team When Google SSO Authorization Expires (Issue #143)

Can you elaborate on how you have integrated Google IdP here please:

  *   From a TEAM portal standpoint
  *   From an IdC portal Standpoint

Can you elaborate on all requested permissions in Teams that were obtained using the expired token become dysfunctional can you:

  *   Describe the behavior? What works? What fails? What would be the expected behavior?
  *   Add log of the issue? Error messages?

Thanks

**Comment by vo-va** [comment]
.
