### ISSUE TITLE
Feature Request: Ticket numbers to links

### ISSUE THREAD

**Issue by jarrod-mg** [aws-samples/iam-identity-center-team#180]
It would be great to be able to turn any reference to a ticket into a link. This would help particularly with approvers, so they can just clink a link to see more details about the request.

This could be as simple as a setting like "Ticket Link Format", which I might set to something like "https://mycompany.atlassian.net/browse/%s" - and then in the UI, any time you emit a ticket number, run it through a printf (or similar) with the ticket link format, in an `<a href="..." />`.

**Comment by reidca** [comment]
This would be useful. Having a single field is not helpful when relevant tickets may exist in more than one system.

**Comment by matthewcbaker** [comment]
From what I see, the two comments above from @jarrod-mg and @reidca are actually referencing several independent points.

As I see it, the request can be split into:
1. Users being able to add multiple ticket numbers to the same request
2. Users being able to select the system that the ticket references
3. To have links generated from ticket numbers using a formatting rule
4. To ensure the ticket numbers are in a set format

Each one of these could technically be implemented totally independently, but having all of them would make a fantastic addition to the system.

---

A suggestion I have for a solution to the above would be along the lines of:
- From the configuration side:
  - Be able to create a list of systems (since there is a list then would presumably need to be done as separate pages in the same way as the approver/eligibility lists, but maybe a better way is possible), each with:
    - Name
    - Format of tickets (to restrict to "0-9 only", or have "text then a dash then digits", etc)
    - URL for formatting rule (if one is not entered then it just displays without)
  - Select whether users can select:
    - A single ticket (i.e if their is more than one system configured then show them a dropdown for selecting it)
    - A list of tickets, 1 from each system (i.e. show them a static list of fields, one for each system)
    - A list of tickets, multiple from each system (i.e. show them an expandable list, each with a dropdown -- is this feasible in the current system?)
- From a migration point of view:
  - A single entry could be created just called 'Ticket' with no URL or restriction set
  - 'Single ticket' could be selected in the configuration

---

Regarding how we solve this currently, we have asked users to add a ticket number, followed by URL, i.e for the URL that @jarrod-mg gave then entering :
- 12345 https://mycompany.atlassian.net/browse/12345

This is obviously a bit messy, and we have already seen plenty of user errors when entering it.  These kind of enhancements would really help a lot.

**Comment by matthewcbaker** [comment]
This is still a useful enhancement, as we
- use multiple ticket systems
- would like automatic links to the actual tickets

**Comment by matthewcbaker** [comment]
I do see this as still useful

**Comment by mbaker-itrs** [comment]
I do still see this as useful due to the wide variation of ticket number formats and systems that end up being entered.

However, I saw that it was closing and let it auto-close as it's not enough of a priority - there are far more important tickets open that would benefit from being done.
