### ISSUE TITLE
Elevated access not visible for admins/auditors if no approval is required

### ISSUE THREAD

**Issue by lvthillo** [aws-samples/iam-identity-center-team#61]
**Describe the bug**

When you configure: `Approval required -> No` in global settings, then people can request access without approval, but it seems that their sessions are not visible to TEAM administrators in the Elevated Access section, although they are stored in DynamoDB and visible to the user itself.

They show up when you edit DynamoDB and add your user as `approvers` and `approver_ids` but this raise other issues.

**Comment by lvthillo** [comment]
It seems to work when my SSO admin group is different from my Auditors group.

**Comment by tawoyinfa** [comment]
@lvthillo are you using thesame group for auditors and admins ? As best practise TEAM by design requires different groups for both functions.
TEAM admins only have authorisation to manage policies and global settings and not elevated access. If you disable the approval workflow, only members of the auditor group would be able to view in-progess elevated access.
