### ISSUE TITLE
Cannot update my TEAM app from v1.0.5 to the latest version

### ISSUE THREAD

**Issue by rapides** [aws-samples/iam-identity-center-team#77]
**Describe the bug**

Got the following error message after executing `./update.sh` for the first time:
`An error occurred (ValidationError) when calling the CreateChangeSet operation: Parameters: [CloudTrailAuditLogs] must have values`

Unfortunately, I cannot repeat it because when I repeat the same command I get a different error:
```
...
+ git remote remove origin
+ git remote add origin codecommit::eu-west-1://team-idc-app
+ git remote add team https://github.com/aws-samples/iam-identity-center-team.git
error: remote team already exists.
```

**To Reproduce**
1. Be on version v1.0.5
2. Go to `deployment` directory
3. Update your `parameters.sh` file to have TAGS and CLOUDTRAIL_AUDIT_LOGS specified
4. Execute `./update.sh`
5. See an error 1
6. Execute `./update.sh`
7. See an error 2
8. Execute `./update.sh`
9. See an error 2

**Expected behavior**

It should properly trigger a deployment procedure.

**Comment by lvthillo** [comment]
@rapides error 1 should be fixed [here](https://github.com/aws-samples/iam-identity-center-team/pull/75) but the fix is not (yet) in an official release. What if you just try it from main?

error 2 is caused because your `update.sh` script failed and didn't get to the last step which is:
```
git remote remove team
```

Can you execute this command:
```
git remote remove team
```

checkout the main branch and try again?

**Comment by rapides** [comment]
@lvthillo It worked for me. Thank you so much for your instructions 👍🏻
